site_name: "Project Cards"
site_url: https://network-wrangler.github.io/projectcard
repo_url: https://github.com/network-wrangler/projectcard

nav:
    - 'index.md'
    - 'schemas.md'
    - 'api.md'
    - 'examples.md'

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
  palette:
    - scheme: default
      primary: blue grey
      accent: deep purple

plugins:
  - autorefs
  - awesome-pages
  - mike
  - macros
  - mermaid2:
      securityLevel: 'loose'
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: true
            show_source: true
            heading_level: 3
      custom_templates: templates
      watch:
        - projectcard
  - search

extra:
  version:
    provider: mike
    default: latest

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js
  - https://code.jquery.com/jquery-3.4.1.min.js
  - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js
  - javascript/schema_doc.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
  - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css
  - extra_css/schema_doc.css
  - extra_css/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - fontawesome_markdown
  - meta
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - smarty
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
