name: Push Workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Document branch
      run: echo ${{ github.ref_name }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Configure Git user
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.tests.txt
    - name: Install package
      run: |
        pip install -e .
    - name: Run Ruff
      run: ruff check --output-format=github .
    - name: Run tests with coverage
      run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=projectcard tests/ | tee pytest-coverage.txt
    - name: Pytest coverage comment
      if: github.event_name == 'pull_request'
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
    - name: Install docs dependencies
      run: |
        pip install -r docs/requirements.txt
    - name: Build docs
      run: |
        mike deploy --push --rebase ${{ github.ref_name }}
